# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('dtype', models.IntegerField(choices=[('高价位', 1), ('低价位', 0)], default=1)),
            ],
            options={
                'verbose_name': '黄金高低位价格时间表',
                'db_table': 'gold_price',
            },
        ),
        migrations.AlterUniqueTogether(
            name='goldprice',
            unique_together=set([('date', 'dtype')]),
        ),
    ]
