# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noble_metal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='dtype',
            field=models.IntegerField(choices=[(1, '高价位'), (0, '低价位')], default=1),
        ),
    ]
