# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noble_metal', '0002_auto_20170411_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='time',
            field=models.TimeField(),
        ),
    ]
